resources:
  - 01-namespace.yaml
  - 02-pod.yaml
  - 03-multi-container-redis.yaml
  - 04-multi-container.yaml
  - 05-annotations.yaml
  - 07-env.yaml
  - 08-config-map.yaml
  - 10-secret.yaml
  - 12-service.yaml
  - 13-service-np.yaml
  - 14-service-lb.yaml
  - 15-replicaset.yaml
  - 16-deployment.yaml
  - 17-statefulset.yaml
  - 19-live-readiness.yaml
  - 20-network-policy.yaml

# kubectl apply -k base/